[package]
name = "bevy_iroh"
version = "0.1.0"
description = "Bevy plugin for peer-to-peer multiplayer games using iroh"
repository = "https://github.com/n0-computer/bevy_iroh"
documentation = "https://docs.rs/bevy_iroh"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "networking", "p2p", "bevy", "plugin"]
categories = ["game-development", "network-programming"]
readme = "README.md"
exclude = ["assets/"]

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = ["bevy_log"] }
iroh = "1"
tokio = { version = "1.36.0", features = ["sync", "rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
futures-util = "0.3.24"
bytes = "1.5.0"
thiserror = "1.0.37"

# Optional
bincode = { version = "2.0.1", optional = true, features = ["serde"] }
serde = { version = "1.0.145", optional = true, features = ["derive"] }

[features]
default = ["client", "server", "recv_channels", "shared-client-id"]

client = []
server = []

recv_channels = []
shared-client-id = []
bincode-messages = ["bincode", "serde"]

[dev-dependencies]
bevy = { version = "0.18.0", default-features = false, features = [
	"bevy_asset",
	"bevy_audio",
	"vorbis",
	"bevy_window",
	"bevy_render",
	"bevy_sprite",
	"bevy_sprite_render",
	"bevy_ui",
	"bevy_ui_render",
	"bevy_state",
	"bevy_text",
	"bevy_core_pipeline",
	"serialize",
	"x11",
] }
rand = "0.8.5"
strum = { version = "0.27.2", features = ["derive"] }

[[example]]
name = "breakout"
path = "examples/breakout/breakout.rs"
required-features = ["bincode-messages"]

[[example]]
name = "chat-server"
path = "examples/chat/server.rs"
required-features = ["bincode-messages"]

[[example]]
name = "chat-client"
path = "examples/chat/client.rs"
required-features = ["bincode-messages"]
